name: String to Matrix
# Given a comma (,) delimited string, transform to a matrix
on: [push]
jobs:
  split_str:
    runs-on: ubuntu-latest
    outputs:
      list_value: ${{ steps.split_comma_string.outputs.list_value }}
    steps:
      - id: split_comma_string
        run: echo "::set-output name=list_value::{\"include\":[{\"version\":\"1.4-esm_interface\"},{\"version\":\"1.4-recom-awicm\"},{\"version\":\"1.4-recom-mocsy-slp\"},{\"version\":\"1.4\"},{\"version\":\"2.0-jio\"},{\"version\":\"2.0-o\"},{\"version\":\"2.0-paleodyn\"},{\"version\":\"2.0-r\"},{\"version\":\"2.0\"},{\"version\":\"2.1\"}]}"

  print_matrix_values:
    needs: split_str
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.split_str.outputs.list_value)}}
    steps:
      - run: echo "The current value is ${{ matrix.version }}"
